media:
  input: src/media
  output: /media
content:
  - name: swim-school-groups
    label: Simskola
    type: collection
    path: src/content/swim-school
    filename: "{primary}.md"
    view:
      fields: [ title, order ]
      primary: title
      sort: [ order, title ]
      default: { sort: order, order: asc }
    fields:
      - { name: title, label: Namn, type: string, required: true }
      - { name: order, label: Order, type: number }
      - { name: body, label: Beskrivning, type: rich-text }
  - name: training-groups
    label: Träningsgrupper
    type: collection
    path: src/content/training-groups
    filename: "{primary}.md"
    view:
      fields: [ title, order ]
      primary: title
      sort: [ order, title ]
      default: { sort: order, order: asc }
    fields:
      - { name: title, label: Namn, type: string, required: true }
      - { name: description, label: Kort beskrivning, type: string, options: { maxlength: 180 }}
      - { name: order, label: Order, type: number }
      - { name: body, label: Beskrivning, type: rich-text }
  - name: club-info
    label: Föreningsinformation
    type: collection
    path: src/content/club
    filename: "{primary}.md"
    view:
      fields: [ title, order ]
      primary: title
      sort: [ order, title ]
      default: { sort: order, order: asc }
    fields:
      - { name: title, label: Namn, type: string, required: true }
      - { name: description, label: Kort beskrivning, type: string, options: { maxlength: 180 }}
      - { name: order, label: Order, type: number }
      - { name: body, label: Beskrivning, type: rich-text }
  - name: site
    label: Site settings
    path: src/_data/site.json
    type: file
    fields:
      - name: title
        label: Titel
        type: string
      - name: description
        label: Hemsidans beskrivning
        type: string
      - name: url
        label: Hemsidans URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
  - name: club
    label: Föreningen
    path: src/foreningen.md
    type: file