# fly.toml app configuration file generated for alvestass-trailbase on 2026-04-16T12:30:06+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'alvestass-trailbase'
primary_region = 'arn'

[build]
  dockerfile = 'Dockerfile'

[[mounts]]
  source = 'trailbase_data'
  destination = '/app/traildepot'

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
